name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1.5.0
      with:
        elixir-version: '1.11.2' # Define the elixir version [required]
        otp-version: '23' # Define the OTP version [required]
        experimental-otp: true
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Compile Warnings as Errors
      run: mix do compile --warnings-as-errors
    - name: Static code analysis step
      run: mix credo -a
    - name: Ensure formatted code
      run: mix format --check-formatted
    - name: Run tests
      run: mix test
    - name: Test coverage
      run: mix coveralls.github --umbrella